"""Human-readable table specifications used for schema documentation."""

from __future__ import annotations

from dataclasses import dataclass

from .constants import CANONICAL_LAYER, FEATURE_LAYER, RAW_LAYER


@dataclass(frozen=True)
class FieldSpec:
    name: str
    dtype: str
    description: str
    nullable: bool = False


@dataclass(frozen=True)
class TableSpec:
    name: str
    layer: str
    description: str
    primary_key: tuple[str, ...]
    foreign_keys: tuple[str, ...]
    fields: tuple[FieldSpec, ...]


TABLE_SPECS: tuple[TableSpec, ...] = (
    TableSpec(
        name="raw_document",
        layer=RAW_LAYER,
        description="Traceable registry of every imported source file together with the raw payload and discovery metadata.",
        primary_key=("raw_document_id",),
        foreign_keys=("dataset_id -> dataset.dataset_id",),
        fields=(
            FieldSpec("raw_document_id", "TEXT", "Stable document identifier."),
            FieldSpec("dataset_id", "TEXT", "Owning dataset root."),
            FieldSpec("dataset_code", "TEXT", "Human-readable dataset code."),
            FieldSpec("dataset_family", "TEXT", "Dataset family such as INRC_II or SCHEDULING_BENCHMARKS."),
            FieldSpec("problem_mode", "TEXT", "STATIC, MULTISTAGE, or STATIC_AND_MULTISTAGE."),
            FieldSpec("source_file", "TEXT", "Absolute source file path."),
            FieldSpec("relative_path", "TEXT", "Path relative to the dataset root."),
            FieldSpec("source_format", "TEXT", "Physical source format such as xml or text."),
            FieldSpec("source_group_code", "TEXT", "Family-specific grouping code such as a case id.", nullable=True),
            FieldSpec("preferred_canonical_source", "INTEGER", "Whether this document is the canonical source for normalized import."),
            FieldSpec("paired_raw_document_id", "TEXT", "Paired companion source document when applicable.", nullable=True),
            FieldSpec("scenario_folder_code", "TEXT", "Folder alias that groups related XML files.", nullable=True),
            FieldSpec("instance_dir_name", "TEXT", "Solution folder name when the XML belongs to an explicit instance.", nullable=True),
            FieldSpec("file_role", "TEXT", "Discovered role such as scenario, history, week, solution, or static case."),
            FieldSpec("root_tag", "TEXT", "XML root tag after namespace normalization when applicable.", nullable=True),
            FieldSpec("scenario_id_in_xml", "TEXT", "Scenario identifier declared inside the XML.", nullable=True),
            FieldSpec("scenario_token_in_name", "TEXT", "Scenario token derived from the file name.", nullable=True),
            FieldSpec("file_code", "INTEGER", "History variant, week file code, or solution week-file code when applicable.", nullable=True),
            FieldSpec("native_case_code", "TEXT", "Native static case code when applicable.", nullable=True),
            FieldSpec("content_sha256", "TEXT", "Digest of the raw payload."),
            FieldSpec("raw_payload", "TEXT", "Original source payload kept for auditability."),
        ),
    ),
    TableSpec(
        name="dataset",
        layer=CANONICAL_LAYER,
        description="Top-level dataset collection such as benchmark, test, or SchedulingBenchmarks roots.",
        primary_key=("dataset_id",),
        foreign_keys=(),
        fields=(
            FieldSpec("dataset_id", "TEXT", "Stable dataset identifier."),
            FieldSpec("dataset_code", "TEXT", "Short code such as benchmark or test."),
            FieldSpec("dataset_family", "TEXT", "Dataset family such as INRC_II or SCHEDULING_BENCHMARKS."),
            FieldSpec("problem_mode", "TEXT", "STATIC, MULTISTAGE, or STATIC_AND_MULTISTAGE."),
            FieldSpec("display_name", "TEXT", "Human-readable dataset name."),
            FieldSpec("root_path", "TEXT", "Resolved root folder used by discovery."),
            FieldSpec("scan_root_path", "TEXT", "Resolved folder actually scanned for source files."),
            FieldSpec("is_test_dataset", "INTEGER", "Boolean flag for solution-bearing test datasets."),
        ),
    ),
    TableSpec(
        name="scenario",
        layer=CANONICAL_LAYER,
        description="Scenario-wide static benchmark description.",
        primary_key=("scenario_id",),
        foreign_keys=("dataset_id -> dataset.dataset_id",),
        fields=(
            FieldSpec("scenario_id", "TEXT", "Scenario identifier from XML."),
            FieldSpec("dataset_id", "TEXT", "Owning dataset collection."),
            FieldSpec("dataset_name", "TEXT", "Dataset code repeated for readability."),
            FieldSpec("planning_horizon_weeks", "INTEGER", "Declared number of weeks in the scenario horizon."),
            FieldSpec("source_file", "TEXT", "Source scenario XML path."),
            FieldSpec("scenario_folder_code", "TEXT", "Folder alias used on disk."),
        ),
    ),
    TableSpec(
        name="skill",
        layer=CANONICAL_LAYER,
        description="Skill catalog scoped to a scenario.",
        primary_key=("skill_id",),
        foreign_keys=("scenario_id -> scenario.scenario_id",),
        fields=(
            FieldSpec("skill_id", "TEXT", "Stable skill identifier."),
            FieldSpec("scenario_id", "TEXT", "Owning scenario.", nullable=True),
            FieldSpec("skill_code", "TEXT", "Original skill code."),
        ),
    ),
    TableSpec(
        name="contract",
        layer=CANONICAL_LAYER,
        description="Contract rules that later drive hard and soft constraints.",
        primary_key=("contract_id",),
        foreign_keys=("scenario_id -> scenario.scenario_id",),
        fields=(
            FieldSpec("contract_id", "TEXT", "Stable contract identifier."),
            FieldSpec("scenario_id", "TEXT", "Owning scenario."),
            FieldSpec("contract_code", "TEXT", "Original contract code."),
            FieldSpec("min_total_assignments", "INTEGER", "Minimum assignments over the planning horizon."),
            FieldSpec("max_total_assignments", "INTEGER", "Maximum assignments over the planning horizon."),
            FieldSpec("min_consecutive_work_days", "INTEGER", "Minimum consecutive working days."),
            FieldSpec("max_consecutive_work_days", "INTEGER", "Maximum consecutive working days."),
            FieldSpec("min_consecutive_days_off", "INTEGER", "Minimum consecutive days off."),
            FieldSpec("max_consecutive_days_off", "INTEGER", "Maximum consecutive days off."),
            FieldSpec("max_working_weekends", "INTEGER", "Maximum working weekends."),
            FieldSpec("complete_weekend_required", "INTEGER", "Whether complete weekends are required."),
        ),
    ),
    TableSpec(
        name="nurse",
        layer=CANONICAL_LAYER,
        description="Nurse master data linked to a single contract.",
        primary_key=("nurse_id",),
        foreign_keys=("scenario_id -> scenario.scenario_id", "contract_id -> contract.contract_id"),
        fields=(
            FieldSpec("nurse_id", "TEXT", "Stable nurse identifier."),
            FieldSpec("scenario_id", "TEXT", "Owning scenario."),
            FieldSpec("nurse_code", "TEXT", "Original nurse code."),
            FieldSpec("contract_id", "TEXT", "Linked contract."),
        ),
    ),
    TableSpec(
        name="nurse_skill",
        layer=CANONICAL_LAYER,
        description="Eligibility relation between nurses and skills.",
        primary_key=("nurse_id", "skill_id"),
        foreign_keys=("nurse_id -> nurse.nurse_id", "skill_id -> skill.skill_id"),
        fields=(
            FieldSpec("nurse_id", "TEXT", "Linked nurse."),
            FieldSpec("skill_id", "TEXT", "Linked skill."),
        ),
    ),
    TableSpec(
        name="shift_type",
        layer=CANONICAL_LAYER,
        description="Shift-type catalog and same-shift run limits.",
        primary_key=("shift_type_id",),
        foreign_keys=("scenario_id -> scenario.scenario_id",),
        fields=(
            FieldSpec("shift_type_id", "TEXT", "Stable shift identifier."),
            FieldSpec("scenario_id", "TEXT", "Owning scenario."),
            FieldSpec("shift_code", "TEXT", "Original shift code."),
            FieldSpec("min_consecutive_shift_assignments", "INTEGER", "Minimum same-shift run length."),
            FieldSpec("max_consecutive_shift_assignments", "INTEGER", "Maximum same-shift run length."),
        ),
    ),
    TableSpec(
        name="forbidden_shift_succession",
        layer=CANONICAL_LAYER,
        description="Dense succession matrix between consecutive working-day shift types.",
        primary_key=("scenario_id", "prev_shift_type_id", "next_shift_type_id"),
        foreign_keys=(
            "scenario_id -> scenario.scenario_id",
            "prev_shift_type_id -> shift_type.shift_type_id",
            "next_shift_type_id -> shift_type.shift_type_id",
        ),
        fields=(
            FieldSpec("scenario_id", "TEXT", "Owning scenario."),
            FieldSpec("prev_shift_type_id", "TEXT", "Preceding shift."),
            FieldSpec("next_shift_type_id", "TEXT", "Candidate succeeding shift."),
            FieldSpec("is_forbidden", "INTEGER", "Boolean flag indicating whether the succession is forbidden."),
        ),
    ),
    TableSpec(
        name="week",
        layer=CANONICAL_LAYER,
        description="Reusable week file imported from a `WD` XML document.",
        primary_key=("week_id",),
        foreign_keys=("scenario_id -> scenario.scenario_id",),
        fields=(
            FieldSpec("week_id", "TEXT", "Stable week-file identifier."),
            FieldSpec("scenario_id", "TEXT", "Owning scenario."),
            FieldSpec("week_index", "INTEGER", "Week file code derived from the filename."),
            FieldSpec("week_code", "TEXT", "String form of the week file code."),
            FieldSpec("source_file", "TEXT", "Source week XML path."),
        ),
    ),
    TableSpec(
        name="day",
        layer=CANONICAL_LAYER,
        description="Seven-day structure attached to each reusable week file.",
        primary_key=("day_id",),
        foreign_keys=("week_id -> week.week_id",),
        fields=(
            FieldSpec("day_id", "TEXT", "Stable day identifier."),
            FieldSpec("week_id", "TEXT", "Owning reusable week file."),
            FieldSpec("day_index", "INTEGER", "0-based weekday index."),
            FieldSpec("day_name", "TEXT", "Long weekday label."),
            FieldSpec("day_short_name", "TEXT", "Short weekday label."),
            FieldSpec("is_weekend", "INTEGER", "Weekend flag."),
        ),
    ),
    TableSpec(
        name="coverage_requirement",
        layer=CANONICAL_LAYER,
        description="Required staffing per reusable week, day, shift, and skill.",
        primary_key=("requirement_id",),
        foreign_keys=(
            "week_id -> week.week_id",
            "day_id -> day.day_id",
            "shift_type_id -> shift_type.shift_type_id",
            "skill_id -> skill.skill_id",
        ),
        fields=(
            FieldSpec("requirement_id", "TEXT", "Stable requirement identifier."),
            FieldSpec("week_id", "TEXT", "Reusable week file."),
            FieldSpec("day_id", "TEXT", "Week-local day."),
            FieldSpec("shift_type_id", "TEXT", "Shift type."),
            FieldSpec("skill_id", "TEXT", "Skill."),
            FieldSpec("min_required", "INTEGER", "Hard minimum coverage."),
            FieldSpec("optimal_required", "INTEGER", "Soft optimal coverage."),
        ),
    ),
    TableSpec(
        name="nurse_request",
        layer=CANONICAL_LAYER,
        description="Week-local off requests that later feed preference penalties.",
        primary_key=("request_id",),
        foreign_keys=(
            "week_id -> week.week_id",
            "nurse_id -> nurse.nurse_id",
            "day_id -> day.day_id",
            "requested_off_shift_type_id -> shift_type.shift_type_id",
        ),
        fields=(
            FieldSpec("request_id", "TEXT", "Stable request identifier."),
            FieldSpec("week_id", "TEXT", "Reusable week file."),
            FieldSpec("nurse_id", "TEXT", "Requested nurse."),
            FieldSpec("day_id", "TEXT", "Requested day."),
            FieldSpec("requested_off_shift_type_id", "TEXT", "Specific unwanted shift when present.", nullable=True),
            FieldSpec("request_type", "TEXT", "OFF_ANY or OFF_SHIFT."),
        ),
    ),
    TableSpec(
        name="history_snapshot",
        layer=CANONICAL_LAYER,
        description="Initial histories from XML plus derived post-week snapshots for explicit instances.",
        primary_key=("history_id",),
        foreign_keys=("scenario_id -> scenario.scenario_id", "instance_id -> instance.instance_id"),
        fields=(
            FieldSpec("history_id", "TEXT", "Stable history snapshot identifier."),
            FieldSpec("scenario_id", "TEXT", "Owning scenario."),
            FieldSpec("instance_id", "TEXT", "Linked explicit instance when the snapshot is instance-specific.", nullable=True),
            FieldSpec("week_index_before_solve", "INTEGER", "Stage index whose solve starts from this snapshot."),
            FieldSpec("source_file", "TEXT", "Originating XML path when applicable.", nullable=True),
            FieldSpec("snapshot_type", "TEXT", "INITIAL_SOURCE, INSTANCE_INITIAL, or DERIVED_POST_WEEK."),
            FieldSpec("history_variant_code", "TEXT", "Original history variant code when applicable.", nullable=True),
        ),
    ),
    TableSpec(
        name="nurse_history_state",
        layer=CANONICAL_LAYER,
        description="Per-nurse rolling counters attached to a history snapshot.",
        primary_key=("history_id", "nurse_id"),
        foreign_keys=(
            "history_id -> history_snapshot.history_id",
            "nurse_id -> nurse.nurse_id",
            "last_shift_type_id -> shift_type.shift_type_id",
        ),
        fields=(
            FieldSpec("history_id", "TEXT", "Owning history snapshot."),
            FieldSpec("nurse_id", "TEXT", "Linked nurse."),
            FieldSpec("last_shift_type_id", "TEXT", "Trailing shift at the end of the previous week.", nullable=True),
            FieldSpec("consecutive_same_shift_count", "INTEGER", "Trailing same-shift count."),
            FieldSpec("consecutive_work_days_count", "INTEGER", "Trailing working-days count."),
            FieldSpec("consecutive_days_off_count", "INTEGER", "Trailing days-off count."),
            FieldSpec("total_worked_shifts_so_far", "INTEGER", "Cumulative assignments so far."),
            FieldSpec("total_working_weekends_so_far", "INTEGER", "Cumulative working weekends so far."),
        ),
    ),
    TableSpec(
        name="instance",
        layer=CANONICAL_LAYER,
        description="Explicit multi-stage instances plus static family instances used by experiment code.",
        primary_key=("instance_id",),
        foreign_keys=(
            "dataset_id -> dataset.dataset_id",
            "scenario_id -> scenario.scenario_id",
            "initial_history_id -> history_snapshot.history_id",
        ),
        fields=(
            FieldSpec("instance_id", "TEXT", "Stable instance identifier."),
            FieldSpec("dataset_id", "TEXT", "Owning dataset."),
            FieldSpec("dataset_family", "TEXT", "Dataset family such as INRC_II or SCHEDULING_BENCHMARKS."),
            FieldSpec("problem_mode", "TEXT", "STATIC or MULTISTAGE."),
            FieldSpec("scenario_id", "TEXT", "Target scenario when the family is INRC-II.", nullable=True),
            FieldSpec("initial_history_id", "TEXT", "Starting history snapshot when the family uses rolling history.", nullable=True),
            FieldSpec("num_weeks", "INTEGER", "Number of stages in the instance."),
            FieldSpec("instance_code", "TEXT", "Human-readable instance code."),
            FieldSpec("native_case_code", "TEXT", "Native static case code when applicable.", nullable=True),
            FieldSpec("instance_dir_name", "TEXT", "Original solution folder name when discovered from disk.", nullable=True),
        ),
    ),
    TableSpec(
        name="instance_week_map",
        layer=CANONICAL_LAYER,
        description="Ordered mapping from instance stage indices to reusable week files.",
        primary_key=("instance_id", "stage_index"),
        foreign_keys=("instance_id -> instance.instance_id", "week_id -> week.week_id"),
        fields=(
            FieldSpec("instance_id", "TEXT", "Owning instance."),
            FieldSpec("stage_index", "INTEGER", "0-based stage index within the instance."),
            FieldSpec("week_id", "TEXT", "Referenced reusable week file."),
        ),
    ),
    TableSpec(
        name="assignment",
        layer=CANONICAL_LAYER,
        description="Observed or produced assignments linked to an instance stage.",
        primary_key=("assignment_id",),
        foreign_keys=(
            "instance_id -> instance.instance_id",
            "week_id -> week.week_id",
            "day_id -> day.day_id",
            "nurse_id -> nurse.nurse_id",
            "shift_type_id -> shift_type.shift_type_id",
            "skill_id -> skill.skill_id",
            "solver_run_id -> solver_run.solver_run_id",
        ),
        fields=(
            FieldSpec("assignment_id", "TEXT", "Stable assignment identifier."),
            FieldSpec("instance_id", "TEXT", "Owning instance."),
            FieldSpec("stage_index", "INTEGER", "Instance stage index needed when the same week file is reused."),
            FieldSpec("week_id", "TEXT", "Referenced reusable week file."),
            FieldSpec("day_id", "TEXT", "Week-local day."),
            FieldSpec("nurse_id", "TEXT", "Assigned nurse."),
            FieldSpec("shift_type_id", "TEXT", "Assigned shift."),
            FieldSpec("skill_id", "TEXT", "Assigned skill."),
            FieldSpec("solver_run_id", "TEXT", "Producing solver run when applicable.", nullable=True),
            FieldSpec("source_file", "TEXT", "Reference solution XML path when applicable.", nullable=True),
            FieldSpec("source_kind", "TEXT", "REFERENCE_SOLUTION or produced solver output."),
        ),
    ),
    TableSpec(
        name="sb_case",
        layer=CANONICAL_LAYER,
        description="Static SchedulingBenchmarks case anchored to one shared experiment instance.",
        primary_key=("sb_case_id",),
        foreign_keys=("dataset_id -> dataset.dataset_id", "instance_id -> instance.instance_id"),
        fields=(
            FieldSpec("sb_case_id", "TEXT", "Stable static-case identifier."),
            FieldSpec("dataset_id", "TEXT", "Owning dataset."),
            FieldSpec("instance_id", "TEXT", "Shared experiment instance for this static case."),
            FieldSpec("case_code", "TEXT", "Native case code such as Instance1."),
            FieldSpec("source_ros_file", "TEXT", "Canonical .ros source path."),
            FieldSpec("source_txt_file", "TEXT", "Paired .txt provenance path."),
            FieldSpec("start_date", "TEXT", "Case start date."),
            FieldSpec("end_date", "TEXT", "Case end date."),
            FieldSpec("horizon_days", "INTEGER", "Number of days in the static horizon."),
            FieldSpec("global_min_rest_minutes", "INTEGER", "Global minimum rest time used to derive shift successions.", nullable=True),
        ),
    ),
    TableSpec(
        name="sb_day",
        layer=CANONICAL_LAYER,
        description="Calendar day structure for a SchedulingBenchmarks static case.",
        primary_key=("sb_day_id",),
        foreign_keys=("sb_case_id -> sb_case.sb_case_id",),
        fields=(
            FieldSpec("sb_day_id", "TEXT", "Stable static-day identifier."),
            FieldSpec("sb_case_id", "TEXT", "Owning static case."),
            FieldSpec("day_index", "INTEGER", "0-based day index in the horizon."),
            FieldSpec("calendar_date", "TEXT", "Resolved calendar date."),
            FieldSpec("day_name", "TEXT", "Weekday label."),
            FieldSpec("day_of_week_index", "INTEGER", "Python weekday index where Monday is 0."),
            FieldSpec("is_weekend", "INTEGER", "Weekend flag."),
        ),
    ),
    TableSpec(
        name="sb_shift_type",
        layer=CANONICAL_LAYER,
        description="Shift catalog for a SchedulingBenchmarks static case.",
        primary_key=("sb_shift_type_id",),
        foreign_keys=("sb_case_id -> sb_case.sb_case_id",),
        fields=(
            FieldSpec("sb_shift_type_id", "TEXT", "Stable static shift identifier."),
            FieldSpec("sb_case_id", "TEXT", "Owning static case."),
            FieldSpec("shift_code", "TEXT", "Native shift code."),
            FieldSpec("duration_minutes", "INTEGER", "Shift duration in minutes."),
            FieldSpec("start_time", "TEXT", "Shift start time.", nullable=True),
            FieldSpec("end_time", "TEXT", "Derived shift end time.", nullable=True),
            FieldSpec("color", "TEXT", "Optional display color from the source.", nullable=True),
        ),
    ),
    TableSpec(
        name="sb_contract",
        layer=CANONICAL_LAYER,
        description="Native SchedulingBenchmarks contract semantics, including valid shifts and workload limits.",
        primary_key=("sb_contract_id",),
        foreign_keys=("sb_case_id -> sb_case.sb_case_id",),
        fields=(
            FieldSpec("sb_contract_id", "TEXT", "Stable static contract identifier."),
            FieldSpec("sb_case_id", "TEXT", "Owning static case."),
            FieldSpec("contract_code", "TEXT", "Native contract code."),
            FieldSpec("min_rest_minutes", "INTEGER", "Minimum rest time when declared.", nullable=True),
            FieldSpec("min_total_minutes", "INTEGER", "Minimum workload in minutes.", nullable=True),
            FieldSpec("max_total_minutes", "INTEGER", "Maximum workload in minutes.", nullable=True),
            FieldSpec("min_consecutive_shifts", "INTEGER", "Minimum consecutive shifts."),
            FieldSpec("max_consecutive_shifts", "INTEGER", "Maximum consecutive shifts."),
            FieldSpec("min_consecutive_days_off", "INTEGER", "Minimum consecutive days off."),
            FieldSpec("max_working_weekends", "INTEGER", "Maximum working weekends.", nullable=True),
            FieldSpec("valid_shift_codes", "TEXT", "Comma-separated valid shift list.", nullable=True),
            FieldSpec("is_meta_contract", "INTEGER", "Whether the contract is a shared meta-contract such as All."),
        ),
    ),
    TableSpec(
        name="sb_employee",
        layer=CANONICAL_LAYER,
        description="SchedulingBenchmarks employee linked to its native contract.",
        primary_key=("sb_employee_id",),
        foreign_keys=("sb_case_id -> sb_case.sb_case_id", "sb_contract_id -> sb_contract.sb_contract_id"),
        fields=(
            FieldSpec("sb_employee_id", "TEXT", "Stable employee identifier."),
            FieldSpec("sb_case_id", "TEXT", "Owning static case."),
            FieldSpec("employee_code", "TEXT", "Native employee code."),
            FieldSpec("sb_contract_id", "TEXT", "Assigned native contract."),
        ),
    ),
    TableSpec(
        name="sb_employee_shift_limit",
        layer=CANONICAL_LAYER,
        description="Per-employee maximum assignments for each shift type.",
        primary_key=("sb_employee_id", "sb_shift_type_id"),
        foreign_keys=("sb_employee_id -> sb_employee.sb_employee_id", "sb_shift_type_id -> sb_shift_type.sb_shift_type_id"),
        fields=(
            FieldSpec("sb_employee_id", "TEXT", "Linked employee."),
            FieldSpec("sb_shift_type_id", "TEXT", "Linked shift type."),
            FieldSpec("max_assignments", "INTEGER", "Maximum number of assignments of this shift for the employee."),
        ),
    ),
    TableSpec(
        name="sb_fixed_assignment",
        layer=CANONICAL_LAYER,
        description="Hard fixed assignments, including explicit OFF days, for SchedulingBenchmarks cases.",
        primary_key=("sb_fixed_assignment_id",),
        foreign_keys=(
            "sb_case_id -> sb_case.sb_case_id",
            "sb_day_id -> sb_day.sb_day_id",
            "sb_employee_id -> sb_employee.sb_employee_id",
            "sb_shift_type_id -> sb_shift_type.sb_shift_type_id",
        ),
        fields=(
            FieldSpec("sb_fixed_assignment_id", "TEXT", "Stable fixed-assignment identifier."),
            FieldSpec("sb_case_id", "TEXT", "Owning static case."),
            FieldSpec("sb_day_id", "TEXT", "Target day."),
            FieldSpec("sb_employee_id", "TEXT", "Target employee."),
            FieldSpec("sb_shift_type_id", "TEXT", "Assigned shift when not OFF.", nullable=True),
            FieldSpec("assignment_code", "TEXT", "Native assignment code, including '-' for OFF."),
            FieldSpec("is_off", "INTEGER", "Whether this fixed assignment is OFF."),
        ),
    ),
    TableSpec(
        name="sb_request",
        layer=CANONICAL_LAYER,
        description="Unified SchedulingBenchmarks on/off requests with explicit weights.",
        primary_key=("sb_request_id",),
        foreign_keys=(
            "sb_case_id -> sb_case.sb_case_id",
            "sb_day_id -> sb_day.sb_day_id",
            "sb_employee_id -> sb_employee.sb_employee_id",
            "sb_shift_type_id -> sb_shift_type.sb_shift_type_id",
        ),
        fields=(
            FieldSpec("sb_request_id", "TEXT", "Stable request identifier."),
            FieldSpec("sb_case_id", "TEXT", "Owning static case."),
            FieldSpec("sb_day_id", "TEXT", "Target day."),
            FieldSpec("sb_employee_id", "TEXT", "Target employee."),
            FieldSpec("sb_shift_type_id", "TEXT", "Target shift."),
            FieldSpec("request_type", "TEXT", "ON_SHIFT or OFF_SHIFT."),
            FieldSpec("weight", "INTEGER", "Request penalty weight."),
        ),
    ),
    TableSpec(
        name="sb_cover_requirement",
        layer=CANONICAL_LAYER,
        description="Static coverage targets with row-specific under/over penalty weights.",
        primary_key=("sb_cover_requirement_id",),
        foreign_keys=(
            "sb_case_id -> sb_case.sb_case_id",
            "sb_day_id -> sb_day.sb_day_id",
            "sb_shift_type_id -> sb_shift_type.sb_shift_type_id",
        ),
        fields=(
            FieldSpec("sb_cover_requirement_id", "TEXT", "Stable coverage identifier."),
            FieldSpec("sb_case_id", "TEXT", "Owning static case."),
            FieldSpec("sb_day_id", "TEXT", "Target day."),
            FieldSpec("sb_shift_type_id", "TEXT", "Target shift."),
            FieldSpec("min_required", "INTEGER", "Minimum desired coverage."),
            FieldSpec("preferred_required", "INTEGER", "Preferred or upper coverage target."),
            FieldSpec("under_weight", "INTEGER", "Penalty weight for understaffing."),
            FieldSpec("over_weight", "INTEGER", "Penalty weight for overstaffing."),
        ),
    ),
    TableSpec(
        name="sb_assignment",
        layer=CANONICAL_LAYER,
        description="Placeholder table for persisted SchedulingBenchmarks solver outputs.",
        primary_key=("sb_assignment_id",),
        foreign_keys=(
            "instance_id -> instance.instance_id",
            "sb_case_id -> sb_case.sb_case_id",
            "sb_day_id -> sb_day.sb_day_id",
            "sb_employee_id -> sb_employee.sb_employee_id",
            "sb_shift_type_id -> sb_shift_type.sb_shift_type_id",
            "solver_run_id -> solver_run.solver_run_id",
        ),
        fields=(
            FieldSpec("sb_assignment_id", "TEXT", "Stable static assignment identifier."),
            FieldSpec("instance_id", "TEXT", "Owning static instance."),
            FieldSpec("sb_case_id", "TEXT", "Owning static case."),
            FieldSpec("sb_day_id", "TEXT", "Assigned day."),
            FieldSpec("sb_employee_id", "TEXT", "Assigned employee."),
            FieldSpec("sb_shift_type_id", "TEXT", "Assigned shift."),
            FieldSpec("solver_run_id", "TEXT", "Producing solver run when applicable.", nullable=True),
            FieldSpec("source_file", "TEXT", "External source file when applicable.", nullable=True),
            FieldSpec("source_kind", "TEXT", "REFERENCE_SOLUTION or produced solver output."),
        ),
    ),
    TableSpec(
        name="solver_run",
        layer=CANONICAL_LAYER,
        description="Experiment run registry for future exact, heuristic, and learning-based solvers.",
        primary_key=("solver_run_id",),
        foreign_keys=("instance_id -> instance.instance_id",),
        fields=(
            FieldSpec("solver_run_id", "TEXT", "Stable solver run identifier."),
            FieldSpec("instance_id", "TEXT", "Solved instance."),
            FieldSpec("algorithm_name", "TEXT", "Primary algorithm family."),
            FieldSpec("variant_name", "TEXT", "Variant or ablation label."),
            FieldSpec("seed", "INTEGER", "Random seed.", nullable=True),
            FieldSpec("runtime_sec", "REAL", "Wall-clock runtime in seconds.", nullable=True),
            FieldSpec("status", "TEXT", "Run status."),
        ),
    ),
    TableSpec(
        name="constraint_result",
        layer=CANONICAL_LAYER,
        description="Constraint-wise evaluation output for a solver run.",
        primary_key=("constraint_result_id",),
        foreign_keys=("solver_run_id -> solver_run.solver_run_id", "week_id -> week.week_id", "nurse_id -> nurse.nurse_id"),
        fields=(
            FieldSpec("constraint_result_id", "TEXT", "Stable constraint-result identifier."),
            FieldSpec("solver_run_id", "TEXT", "Evaluated solver run."),
            FieldSpec("week_id", "TEXT", "Target week file when the result is week-specific.", nullable=True),
            FieldSpec("nurse_id", "TEXT", "Target nurse when the result is nurse-specific.", nullable=True),
            FieldSpec("constraint_code", "TEXT", "Constraint label."),
            FieldSpec("violation_count", "INTEGER", "Count of violations."),
            FieldSpec("penalty_cost", "REAL", "Penalty contribution."),
            FieldSpec("is_hard", "INTEGER", "Hard/soft flag."),
            FieldSpec("evaluation_scope", "TEXT", "INSTANCE, STAGE, NURSE, or similar scope label."),
        ),
    ),
    TableSpec(
        name="ablation_result",
        layer=CANONICAL_LAYER,
        description="Placeholder table for comparative ablation reporting.",
        primary_key=("ablation_result_id",),
        foreign_keys=("solver_run_id -> solver_run.solver_run_id",),
        fields=(
            FieldSpec("ablation_result_id", "TEXT", "Stable ablation-result identifier."),
            FieldSpec("solver_run_id", "TEXT", "Associated solver run."),
            FieldSpec("ablation_group", "TEXT", "Ablation family or study grouping."),
            FieldSpec("metric_name", "TEXT", "Metric name."),
            FieldSpec("metric_value", "REAL", "Metric value."),
            FieldSpec("notes", "TEXT", "Optional notes.", nullable=True),
        ),
    ),
    TableSpec(
        name="roster_day_view",
        layer=FEATURE_LAYER,
        description="Dense nurse-day-stage roster with explicit OFF rows.",
        primary_key=(),
        foreign_keys=(),
        fields=(),
    ),
    TableSpec(
        name="coverage_summary_view",
        layer=FEATURE_LAYER,
        description="Coverage requirements versus assigned counts for each instance stage, day, shift, and skill.",
        primary_key=(),
        foreign_keys=(),
        fields=(),
    ),
    TableSpec(
        name="nurse_week_summary_view",
        layer=FEATURE_LAYER,
        description="Per-nurse weekly workload, weekend, request-violation, and fairness summaries.",
        primary_key=(),
        foreign_keys=(),
        fields=(),
    ),
    TableSpec(
        name="history_transition_view",
        layer=FEATURE_LAYER,
        description="Transition of rolling history counters between consecutive instance stages.",
        primary_key=(),
        foreign_keys=(),
        fields=(),
    ),
)
